import type { NextPage } from 'next';
import Head from 'next/head';
import { useRequest } from '../src/hooks';

import { UserService } from '../src/services';

const Home: NextPage = () => {
  const { data: me } = useRequest(UserService.me, {
    // refetchInterval: 500,
  });

  return (
    <div>
      <Head>
        <title>NUMBLE::</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
